//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Detalle
    {
        public int Id_DetFac { get; set; }
        public int Id_Prod { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
        public int Id_Fac { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Factura Factura { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Producto Producto { get; set; }
    }
}
